name: iot_firebase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_database:
  get: 4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        # - asset: assets/fonts/SF-Pro-Display-ThinItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        # - asset: assets/fonts/SF-Pro-Display-LightItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
